services:
  # Backend service with integrated frontend build
  - type: web
    name: tech-interview-analyzer
    env: node
    plan: free
    buildCommand: |
      # Instalar dependencias del servidor
      npm install
      
      # Arreglar vulnerabilidades de seguridad (no bloqueante)
      npm audit fix || true
      
      # Crear directorio de uploads si no existe
      mkdir -p uploads
      
      # Verificar archivos estáticos del cliente
      mkdir -p client/public/static/media
      
      # Si no existen los iconos, crear placeholders
      if [ ! -f "client/public/favicon.ico" ]; then
        echo "Creating placeholder favicon.ico"
        touch client/public/favicon.ico
      fi
      
      if [ ! -f "client/public/logo192.png" ]; then
        echo "Creating placeholder logo192.png"
        touch client/public/logo192.png
      fi
      
      if [ ! -f "client/public/logo512.png" ]; then
        echo "Creating placeholder logo512.png"
        touch client/public/logo512.png
      fi
      
      # Listar contenido del directorio public para debug
      echo "Contents of client/public directory:"
      ls -la client/public
      
      # Instalar y construir el frontend
      cd client && npm install && npm audit fix || true && npm run build && cd ..
      
      # Verificar que el build se creó correctamente
      echo "Contents of client/build directory:"
      ls -la client/build
    startCommand: |
      # Verificar dependencias antes de iniciar
      if [ ! -d "node_modules" ]; then
        echo "Installing missing server dependencies..."
        npm install
      fi
      
      if [ ! -d "client/node_modules" ]; then
        echo "Installing missing client dependencies..."
        cd client && npm install && cd ..
      fi
      
      if [ ! -d "client/build" ]; then
        echo "Client build directory not found, creating it..."
        cd client && npm run build && cd ..
      fi
      
      # Crear directorio de uploads si no existe
      mkdir -p uploads
      
      # Iniciar el servidor
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true

  # Frontend static site
  - type: web
    name: tech-interview-analyzer
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: tech-interview-analyzer-api
          type: web
          property: url
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable 