services:
  # Backend service with integrated frontend build
  - type: web
    name: tech-interview-analyzer
    env: node
    plan: free
    buildCommand: |
      # Instalar dependencias del servidor
      npm install
      
      # Crear directorio de uploads si no existe
      mkdir -p uploads
      
      # Instalar y construir el frontend
      cd client && npm install && npm run build && cd ..
      
      # Verificar que el build se creó correctamente
      ls -la client/build
    startCommand: |
      # Verificar dependencias antes de iniciar
      if [ ! -d "node_modules" ]; then
        echo "Installing missing server dependencies..."
        npm install
      fi
      
      if [ ! -d "client/node_modules" ]; then
        echo "Installing missing client dependencies..."
        cd client && npm install && cd ..
      fi
      
      if [ ! -d "client/build" ]; then
        echo "Client build directory not found, creating it..."
        cd client && npm run build && cd ..
      fi
      
      # Crear directorio de uploads si no existe
      mkdir -p uploads
      
      # Iniciar el servidor
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true

  # Frontend static site
  - type: web
    name: tech-interview-analyzer
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: tech-interview-analyzer-api
          type: web
          property: url
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable 